# Generated by Django 5.2.12 on 2026-03-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('planning', 'Planning')], default='planning', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('team_size', models.IntegerField(default=1)),
                ('ai_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('analyst', 'Analyst')], max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('avatar_initials', models.CharField(blank=True, max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('ai_productivity_score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['name'],
            },
        ),
    ]
